; Program: High res Bitmap
; Author: Andrew Burch
; Site: www.0xc64.com
; Assembler: win2c64
; Notes: Display high resolution
;       2 Colours per character bitmap
;

                .org $5c00

bitmapcolour    .byte $01, $0d, $05, $05, $05, $05, $05, $05
                .byte $05, $05, $05, $05, $05, $05, $05, $05
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $05, $05, $0d, $01
                .byte $0d, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $0d
                .byte $05, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $05
                .byte $05, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $05
                .byte $05, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $05
                .byte $05, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $05, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $20, $20, $a0, $a0, $20, $20
                .byte $a0, $a0, $20, $20, $a0, $a0, $20, $20
                .byte $a0, $a0, $20, $20, $a0, $a0, $20, $20
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $20, $20, $a0, $a0, $20, $20
                .byte $a0, $a0, $20, $20, $a0, $a0, $20, $20
                .byte $a0, $a0, $20, $20, $a0, $a0, $20, $20
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $a0, $a0, $20, $2a, $a2, $a0
                .byte $20, $20, $a2, $a2, $20, $2a, $a2, $a0
                .byte $20, $2a, $a0, $a0, $2a, $2a, $a0, $a0
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $a0, $a0, $2a, $a2, $2a, $a2
                .byte $2a, $a2, $2a, $a2, $2a, $a2, $2a, $a2
                .byte $2a, $2a, $a0, $a2, $a2, $2a, $a0, $a0
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $20, $20, $2a, $a2, $2a, $a2
                .byte $a0, $2a, $a2, $20, $2a, $a2, $2a, $2a
                .byte $2a, $2a, $2a, $2a, $2a, $a2, $20, $20
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $20, $20, $2a, $a2, $2a, $a2
                .byte $a2, $2a, $a2, $2a, $2a, $a2, $2a, $a2
                .byte $2a, $a2, $a2, $a2, $2a, $2a, $20, $20
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $a0, $a0, $2a, $a2, $2a, $a2
                .byte $2a, $2a, $a2, $a2, $2a, $a2, $2a, $a2
                .byte $2a, $a2, $a2, $a2, $2a, $2a, $a0, $a0
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $a0, $a0, $20, $20, $a0, $a0
                .byte $20, $20, $a0, $a0, $20, $20, $a0, $a0
                .byte $20, $20, $a0, $a0, $20, $20, $a0, $a0
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $20, $20, $a0, $a0, $20, $20
                .byte $a0, $a0, $20, $20, $a0, $a0, $20, $20
                .byte $a0, $a0, $20, $20, $a0, $a0, $20, $20
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $20, $20, $a0, $a0, $20, $20
                .byte $a0, $a0, $20, $20, $a0, $a0, $20, $20
                .byte $a0, $a0, $20, $20, $a0, $a0, $20, $20
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $05, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $05, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $05, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $05
                .byte $05, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $05
                .byte $05, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $05
                .byte $0d, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $0d
                .byte $0b, $0d, $0d, $05, $05, $05, $05, $05
                .byte $05, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $05, $05, $0d, $0f

colourpad       .byte 00, 00, 00, 00, 00, 00, 00, 00
                .byte 00, 00, 00, 00, 00, 00, 00, 00
                .byte 00, 00, 00, 00, 00, 00, 00, 00

bitmapdata      .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $fe
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $3f
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $d3
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $20
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $80
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $00
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $00
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $00
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $00
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $00
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $00
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $00
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $00
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $02
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $04
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $22
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $27
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $40
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $7f
                .byte $fe, $fe, $fe, $ff, $fe, $ff, $fe, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $7f, $7f, $7f, $7f, $ff, $7f, $ff, $7f
                .byte $fe, $fe, $fe, $ff, $fe, $fe, $fe, $fe
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $7f, $7f, $ff, $7f, $7f
                .byte $fe, $fe, $ff, $ff, $ff, $ff, $ff, $fe
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $7f, $7f, $7f, $7f, $7f, $ff, $7f, $7f
                .byte $fe, $fe, $ff, $fe, $fe, $fe, $ff, $fe
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $7f, $ff, $7f, $7f, $ff, $ff, $ff, $ff
                .byte $fe, $fe, $fe, $fe, $fe, $fe, $fe, $fe
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $fe, $fe, $fe, $fe, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $80, $bf, $bf, $bf, $bf, $bf, $bf
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $01, $fd, $fd, $fd, $fd, $fd, $fd
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $f8, $fb
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $1f, $df
                .byte $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
                .byte $fb, $fb, $fb, $fb, $fb, $fb, $fb, $fb
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $fe
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $7f
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $fe
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $1f
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $e0
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $0f
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $07
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $fd, $f8
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $3f
                .byte $df, $df, $df, $df, $df, $df, $df, $df
                .byte $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
                .byte $fb, $fb, $fb, $fb, $fb, $fb, $fb, $fb
                .byte $ff, $ff, $fe, $f8, $f0, $e0, $e0, $c0
                .byte $3f, $ff, $ff, $ff, $ff, $ff, $ff, $f8
                .byte $f8, $fe, $ff, $ff, $ff, $ff, $ff, $1f
                .byte $ff, $ff, $7f, $3f, $1f, $1f, $0f, $07
                .byte $e0, $f0, $f0, $f0, $f8, $fc, $fe, $fe
                .byte $e0, $c0, $e0, $f0, $f8, $f8, $fc, $fc
                .byte $07, $0f, $1f, $1f, $3f, $7f, $fe, $fc
                .byte $0f, $1f, $3f, $7f, $ff, $ff, $ff, $ff
                .byte $ff, $fe, $fc, $f0, $f0, $e0, $e0, $c0
                .byte $7f, $ff, $ff, $ff, $ff, $f0, $e0, $c0
                .byte $fc, $ff, $ff, $ff, $ff, $2f, $07, $03
                .byte $ff, $ff, $ff, $7f, $1f, $1f, $0f, $07
                .byte $fe, $fe, $fc, $fc, $f8, $f8, $f8, $f0
                .byte $07, $0f, $0f, $0f, $1f, $1f, $1f, $3f
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $fe, $fe
                .byte $0f, $1f, $1f, $3f, $7f, $7f, $ff, $ff
                .byte $3f, $1f, $1f, $1f, $1f, $3f, $3f, $3f
                .byte $df, $df, $df, $df, $df, $df, $df, $df
                .byte $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
                .byte $fb, $fb, $fb, $fb, $fb, $fb, $fb, $fb
                .byte $3f, $7f, $7f, $7f, $7c, $fe, $fe, $fc
                .byte $3f, $7f, $7f, $ff, $ff, $ff, $ff, $ff
                .byte $f8, $fc, $fe, $ff, $ff, $ff, $ff, $ff
                .byte $f8, $fc, $fc, $fc, $fe, $fe, $7e, $7e
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $7f, $3f, $1f, $1f, $1f, $3f
                .byte $fc, $f8, $f0, $f0, $e0, $e0, $e0, $f0
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $3f, $7f, $7e, $7e, $fe, $fe, $7e, $fc
                .byte $7f, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $fe, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $07, $1f, $07, $ff, $ff, $ff, $ff, $ff
                .byte $0f, $0f, $1f, $1f, $3f, $3f, $3f, $7f
                .byte $c0, $e0, $fe, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $3f, $1f, $0f, $0f, $07
                .byte $fe, $fc, $f8, $f8, $f0, $e0, $e0, $c0
                .byte $ff, $ff, $f7, $e7, $e7, $c7, $87, $83
                .byte $3f, $3f, $3f, $1f, $1f, $3f, $3f, $1f
                .byte $df, $df, $df, $df, $df, $df, $df, $df
                .byte $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
                .byte $fb, $fb, $fb, $fb, $fb, $fb, $fb, $fb
                .byte $fe, $7e, $7e, $7f, $7f, $3f, $3f, $1f
                .byte $ff, $ff, $ff, $ff, $ff, $7f, $1f, $07
                .byte $ff, $ff, $ff, $fe, $fe, $fc, $f0, $00
                .byte $7e, $fe, $fe, $fc, $fc, $f8, $f8, $f0
                .byte $ff, $ff, $ff, $fe, $fe, $fe, $fc, $f8
                .byte $7f, $7f, $ff, $fd, $fc, $f8, $f0, $f0
                .byte $f0, $f8, $fc, $fe, $fe, $7f, $3f, $3f
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $7f, $3f
                .byte $fe, $7e, $7e, $7f, $3f, $3f, $1f, $1f
                .byte $ff, $ff, $ff, $ff, $ff, $7f, $3f, $07
                .byte $ff, $ff, $ff, $fe, $fc, $fc, $f8, $e0
                .byte $c8, $fc, $fc, $fc, $f8, $f8, $f8, $f0
                .byte $7f, $7f, $7e, $7e, $7e, $7e, $7f, $3f
                .byte $7c, $fe, $ff, $ff, $ff, $ff, $fe, $fe
                .byte $f8, $fc, $7c, $7c, $7c, $7c, $f8, $f8
                .byte $7e, $7f, $7f, $ff, $ff, $ff, $7f, $1f
                .byte $07, $87, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $c0, $c0, $fc, $fc, $fe, $fc, $fc, $f0
                .byte $df, $df, $df, $df, $df, $df, $df, $df
                .byte $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
                .byte $fb, $fb, $fb, $fb, $fb, $fb, $fb, $fb
                .byte $f0, $f0, $f8, $fc, $fe, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $1f, $00, $00
                .byte $ff, $ff, $ff, $ff, $fc, $f0, $00, $00
                .byte $1f, $1f, $3f, $ff, $ff, $ff, $ff, $ff
                .byte $f8, $f0, $e0, $c0, $c0, $f1, $ff, $ff
                .byte $1f, $1f, $3f, $3f, $7f, $ff, $ff, $ff
                .byte $e0, $f0, $f0, $f8, $fc, $ff, $ff, $ff
                .byte $3f, $1f, $1f, $0f, $0f, $ff, $ff, $ff
                .byte $f0, $f8, $fe, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $3f, $00, $00, $00
                .byte $ff, $ff, $ff, $ff, $fc, $f0, $00, $00
                .byte $1f, $3f, $7f, $ff, $ff, $ff, $ff, $ff
                .byte $c0, $e0, $f0, $f8, $fe, $ff, $ff, $ff
                .byte $83, $ff, $ff, $ff, $ff, $fc, $00, $00
                .byte $0f, $0f, $1f, $3f, $ff, $ff, $ff, $ff
                .byte $e0, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $00, $f8, $f8, $f8, $f8, $fc, $ff, $ff
                .byte $1f, $1f, $1f, $1f, $3f, $3f, $ff, $ff
                .byte $df, $df, $df, $df, $df, $df, $df, $df
                .byte $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
                .byte $fb, $fb, $fb, $fb, $fb, $fb, $fb, $fb
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $df, $df, $df, $df, $df, $df, $df, $df
                .byte $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
                .byte $fb, $f8, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $00, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $df, $1f, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $bf, $bf, $bf, $bf, $bf, $bf, $80, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $00, $ff
                .byte $fd, $fd, $fd, $fd, $fd, $fd, $01, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $fe, $ff, $fe, $fe
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $fe, $ff, $fe, $fe, $fe, $fe, $fe, $fe
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $fe, $fe, $fe, $ff, $ff, $ff, $ff, $fe
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $7f, $7f, $ff, $7f
                .byte $fe, $fe, $fe, $fe, $fe, $ff, $fe, $fe
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $7f, $7f, $7f, $ff, $ff, $ff, $ff, $ff
                .byte $fe, $fe, $fe, $ff, $fe, $fe, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $7f, $7f, $7f, $ff, $7f, $7f, $7f, $7f
                .byte $fe, $ff, $fe, $ff, $ff, $fe, $fe, $fe
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $7f, $ff, $ff, $ff, $7f, $7f
                .byte $fe, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $19, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $bf, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $d4, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $00, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $00, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $00, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $02, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $13, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $f4, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $c9, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $7c, $ff, $ff, $ff, $ff, $ff, $ff, $ff
                .byte $7f, $ff, $ff, $ff, $ff, $ff, $ff, $ff

                                   ; sys 32576
                lda #00            ; init background & screen
                sta $d020
                sta $d021

                lda $dd00          ; switch to bank 2
                and #254
                sta $dd00

                lda #59            ; enable bitmap mode (hires only)
                sta $d011

                lda #120           ; set colour map & data pointers
                sta $d018

forever         jmp forever
